name: main

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  run_release_please:
    name: Run release-please
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_release-please.yml@v4.1.0
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
